home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('embaucher/', views.hire, name='hire'),
    path('cv/', views.cv, name='cv'),
    path('embaucher/personnel', views.personal, name='personal'),
    path('travailler/', views.work, name='work'),
    path('centre-de-carriere/', views.career_center, name='career_center'),
    path('contact/', views.contact, name='contact'),
    path('propose/', views.propose, name='propose'),
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', )),
                  path('manager/', include('manager.urls', namespace='manager')),
                  path('admin/', admin.site.urls),
                  path('jobs/', include('jobs.urls', namespace='jobs')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone

from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location='/media/files')


# Create your models here.

class Personnel(models.Model):
    position_type = models.CharField(max_length=100)
    job_category = models.CharField(max_length=100)
    position_title = models.CharField(max_length=100)
    workplace = models.CharField(max_length=100)
    preferred_contact_method = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    message_for_us = models.CharField(max_length=120)
    created = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        self.created = timezone.now()
        return super(Personnel, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.first_name} {self.last_name}, email: {self.email}'

    class Meta:
        verbose_name_plural = 'personnel'


class Cv(models.Model):
    username = models.CharField(max_length=100, null=True)
    password = models.CharField(max_length=100, null=True)
    confirmpassword = models.CharField(max_length=100, null=True)
    firstname = models.CharField(max_length=100, null=True)
    lastname = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    confirmemail = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    location = models.CharField(max_length=100, null=True)
    cv = models.FileField(blank=True, null=True)
    canadanational = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.username)

home/forms.py
from django import forms

from .models import Personnel

# Create your forms here.

class PersonnelForm(forms.ModelForm):
    class Meta:
        model = Personnel
        fields = ('__all__')

home/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

from home.models import Cv
from . import forms

# Create your views here.

def index(request):
    return render(request, 'home/index.html', {})
def contact(request):
    return render(request, 'home/contact.html', {})
def propose(request):
    return render(request, 'home/propose.html', {})

def hire(request):
    return render(request, 'home/embaucher.html', {})
def cv(request):
    if request.method == "POST" and request.FILES['document']:
        username = request.POST.get('username')
        print(username)
        password = request.POST.get('password')
        print(password)
        confirmpassword = request.POST.get('confirmpassword')
        print(confirmpassword)
        firstname = request.POST.get('firstname')

        lastname = request.POST.get('lastname')
        email = request.POST.get('email', '')
        confirmemail = request.POST.get('confirmemail')
        category = request.POST.get('category')
        location = request.POST.get('location')
        
        cv = request.FILES['document']
        fs = FileSystemStorage()
        filename = fs.save(cv.name, cv)

        canadanational = request.POST.get('canadanational')

        savee = Cv(username=username,password=password,confirmpassword=confirmpassword,email=email,confirmemail=confirmemail,firstname=firstname,lastname=lastname,category=category,location=location,cv=cv,)
        savee.save()
        return render(request, 'home/index.html', {})

    return render(request, 'home/cv.html', {})





        # return render(request, 'shop/cv.html')



def work(request):
    return render(request, 'home/travailler.html', {})

def career_center(request):
    return render(request, 'home/centre-de-carriere.html', {})

# Form to receive data
def personal(request):
    if request.method == 'POST':
        form = forms.PersonnelForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'home/personnel_done.html')
    else:
        form = forms.PersonnelForm

    return render(request, 'home/personnel.html', {'form': form})

templates/home/centre-de-carriere.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="row" id="topBanner3" >
	<div class="col 12 col-md-7 content mt-3 pt-3">
		<h1 class="d-none d-xl-block" style="font-size: 86px; margin: -10px 0px 20px 0px; padding: 0px;">CENTRE DE CARRI&Egrave;RE</h1>
		<p class="d-none d-xl-block" style="position: relative; top: 50px; ">Vous avez s&ucirc;rement d&eacute;j&agrave; entendu le dicton, &laquo; On ne na&icirc;t pas gagnant, on le devient &raquo;. Il n&rsquo;y a rien de plus vrai. La concurrence sur le march&eacute; de l&rsquo;emploi peut s&rsquo;av&eacute;rer f&eacute;roce, et souvent, pour &eacute;merger dans un oc&eacute;an de candidats, une bonne pr&eacute;paration est d&eacute;terminante. Un petit coup de pouce de nos experts vous donnera une longueur d&rsquo;avance.</p>
	</div>
</div>


<div id="documents">
	<div class="content mt-4">
		<h2 class="d-none d-xl-block">CONSEILS ET OUTILS</h2>
		<p class="d-none d-xl-block">Si vous recherchez quelques &eacute;l&eacute;ments d&rsquo;information, jetez un coup d&rsquo;&oelig;il &agrave; nos guides pratiques de recherche d&rsquo;emploi et questions de pr&eacute;paration &agrave; l&rsquo;entrevue, ci-dessous. Vous auriez besoin de conseils personnalis&eacute;s? <a href="https://www.jobillico.com/fr/employeurs/quantum/voir-evenements">&eacute;v&eacute;nements &agrave; venir</a>!</p>
		<div id="docList">
			<div class="row listing">
				<div class="item pr-0 pr-md-3"><img src="{% static 'images/doc_56.jpg' %}" alt=""></div>
				<div class="item">
					<h3 class="d-none d-xl-block mb-5">Un CV efficace</h3>
					<p class="d-none d-xl-block">Quelques directives de base pour cr&eacute;er un CV accrocheur. T&eacute;l&eacute;chargez-le.</p>
					<a class="docLink" target="_blank" href="{% static 'pdfs/resumes_that_work__final___fr.pdf' %}">TÉLÉCHARGER</a>
				</div>
			</div>
			<div class="listing">
				<div class="item pr-0 pr-md-3"><img src="{% static 'images/doc_57.jpg' %}" alt=""></div>
				<div class="item">
					<h3 class="d-none d-xl-block mb-5">Pour une entrevue r&eacute;ussie </h3>
					<p class="d-none d-xl-block">Quoi faire avant, durant et apr&egrave;s l&rsquo;entrevue, pour faire une premi&egrave;re bonne impression.</p>
					<a class="docLink" target="_blank" href="{% static 'pdfs/pages_de_interview_success_checklist_2015_final_fr.pdf' %}">TÉLÉCHARGER</a>
				</div>
			</div>
			<div class="listing">
				<div class="item pr-0 pr-md-3"><img src="{% static 'images/doc_58.jpg' %}" alt=""></div>
				<div class="item">
					<h3 class="d-none d-xl-block mb-5">&Eacute;chantillon de questions d&#39;entrevue </h3>
					<p class="d-none d-xl-block">Un bon outil pour vous exercer avant le jour J! Vous y trouverez &agrave; la fois des questions susceptibles de vous &ecirc;tre pos&eacute;es ET celles que vous pourrez poser &agrave; l&rsquo;intervieweur.</p>
					<a class="docLink" target="_blank" href="{% static 'pdfs/pages_de_interview_success_checklist_2015_final_fr_2_page_2.pdf' %}">TÉLÉCHARGER</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="links">
	<div class="content">
		<h2>LIENS IMPORTANTS</h2>
		</div>
		<p class="d-none d-xl-block" style="margin: 10px auto; text-align: center;">Des liens utiles vers des sites Web du gouvernement contenant des renseignements g&eacute;n&eacute;raux sur l&rsquo;admissibilit&eacute; &agrave; l&rsquo;emploi, les &eacute;chelles salariales et vos droits en tant qu&rsquo;employ&eacute;(e).</p>
		<div class="row">
		<a class="impLink" target="_blank" href="https://www.canada.ca/fr/emploi-developpement-social/programmes/normes-travail/normes-federales.html">Normes du travail f&eacute;d&eacute;rales - Gouvernement du Canada</a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="http://www.cnt.gouv.qc.ca/accueil/index.html">Normes du travail du Qu&eacute;bec - CNESST</a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="https://www.labour.gov.on.ca/french/es/index.php">Normes du travail de l&#39;Ontario - Minist&egrave;re du travail </a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="https://www.workplace.ca/laws/">Fiche de consultation - Normes d&#39;emploi par province</a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="https://www.canada.ca/fr/emploi-developpement-social/programmes/sante-securite.html">Sant&eacute; et s&eacute;curit&eacute; du travail - Gouvernement du Canada </a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="http://www.csst.qc.ca/employeurs/accidents-maladies-lesions/procedures-suivis/Pages/procedures-suivis.aspx">Sant&eacute; et s&eacute;curit&eacute; du travail Qu&eacute;bec - CNESST</a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="http://www.wsib.on.ca/">Sant&eacute; et s&eacute;curit&eacute; du travail Ontario - CSPAAT</a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/service-canada.html">Service Canada</a>
		</div>
		<div class="row">
		<a class="impLink" target="_blank" href="http://www.cic.gc.ca/francais/travailler/index.asp">Travailler au Canada (travailleurs &eacute;trangers)</a>
	</div>
</div>


<div id="articles">
	<div class="content">
		<div class="row">
		<a style="margin: 10px auto;" href=""><h2>BLOGUE</h2></a>
		<p style="text-align: center;" class="d-none d-md-block">La mine d&rsquo;informations des chercheurs d&rsquo;emploi et des employ&eacute;s &ndash; de la conciliation travail-famille aux &eacute;valuations de rendement&hellip; en passant par tout le reste. Jetez un coup d&#39;oeil &agrave; notre <!--<a href="https://quantum.ca/blog/?lang=fr">blogue</a> --> !&nbsp;</p>
		</div>
	</div>
</div>
{% endblock %}

templates/home/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<div style=" margin: auto;
  width: 50%;
  border: 3px solid green;
  padding: 10px;">
<h2>Le Plaisir De Soigner Inc.</h2>
<h2>514-992-5092</h2>
<h2>leplaisirdesoignerinc@gmail.com</h2>
</div>
<br>
<br>
<br>
<br>
{% endblock %}

templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="row">
	<div class="col">
		<div id="home1" class="homeSec d-flex flex-column">
			<div id="homeBkgCon">
				<div id="homeSlide">
					<img id="panel1" class="img-fluid" src="{% static 'images/un.png' %}" alt="" usemap="#homeSlide"><map name="homeSlide">
		<area alt="" coords="19,252,314,416" href="{% url 'home:hire' %}">
		<area alt="" coords="706,198,1032,357" href="{% url 'home:work' %}">
		<div id="video1"> <area alt="" coords="81,465,176,532" > </div>

		</map>

				</div>
				<div id="vidCon" class=" hidden mb-5 pb-5 center">
				<video width="1280" height="1280" controls><source src="{% static 'vid/final1.mp4' %}" type="video/mp4"  /></video></div>
			</div>
		</div>
	</div>
</div>
{% comment %} <div class= "row justify-content-center" > 
	<div class="col" allign="center">
		<div id="home2" class= "d-flex flex-column">
			<div class="row justify-content-center">
				<div class="col-1">
					<img class="botArrow prev" onclick="prevBotPanel();" src="{% static 'images/botArrow_prev.jpg' %}" alt="">
				</div>
				<div class="col-6 d-flex flex-column justify-content-center text-center">
					<div id="botSlideCon" class="d-flex text-center">
<!--						<h3>VOS TALENTS, C'EST NOTRE AFFAIRE!</h3>-->
						<div id="botPanel1" class="panel">
<!--							Depuis 1968, Quantum aide les entreprises &agrave; trouver le personnel temporaire, permanent et contractuel dont elles ont besoin pour r&eacute;aliser<br>leurs objectifs de croissance.-->
						</div>
						<div id="botPanel2" class="panel right">
<!--							On ne s'occupe pas seulement de recrutement! Du traitement de la masse salariale &agrave; la gestion sur les lieux, nous offrons des solutions personnalis&eacute;es visant &agrave; r&eacute;pondre &agrave; tous les d&eacute;fis de dotation en RH, m&ecirc;me les plus complexes.-->
						</div>
						<div id="botPanel3" class="panel right">
							Nous savons bien qu'il faut plus que des comp&eacute;tences et de l'exp&eacute;rience sur papier pour &ecirc;tre le bon candidat. Notre processus approfondi de pr&eacute;s&eacute;lection, d'entrevue et d'&eacute;valuation des comp&eacute;tences assure la r&eacute;ussite des embauches.
						</div>
						<div id="botPanel4" class="panel right">
							Nous sommes des experts dans notre domaine. Quantum a mis en place six divisions distinctes, toutes dot&eacute;es de sp&eacute;cialistes dans leur cr&eacute;neau respectif.
						</div>
						<div id="botPanel5" class="panel right">
<!--							Quantum exploite un r&eacute;seau de 12 succursales bien situ&eacute;es, desservant les march&eacute;s de l'emploi du Qu&eacute;bec, de l'Ontario et de la ville de New York.-->
						</div>
						<div id="botPanel6" class="panel right">
<!--							Quantum est fier de soutenir les Fondations canadienne-->
<!--							<br>et qu&eacute;b&eacute;coise du cancer du sein.-->
						</div>
					</div>
				</div>
				<div class="col-1">
					<img class="botArrow next" onclick="nextBotPanel();" src="{% static 'images/botArrow_next.jpg' %}" alt="">
				</div>
			</div>					
		</div>
	</div>
</div> {% endcomment %}
<div class="row justify-content-center mt-4 d-none d-sm-flex">
	<div class="col-9">
		<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner">
			<div class="carousel-item active">
				<div class="carousel-caption">
					<h2 class="text-center">
					VOS TALENTS, C'EST NOTRE AFFAIRE!
					</h2>
					<h4 class="text-justify">
					Depuis 2010, Le Plaisir de Soigner aide les institutions de sante telles que les hôpitaux, les maisons de retraite et les CHSLD à trouver le personnel temporaire et contractuel dont elles ont besoin pour réaliser leurs objectifs de soins de santé.
					</h4>
				</div>
			</div>
			<div class="carousel-item">
				<div class="carousel-caption">
					<h2 class="text-center">
					VOS TALENTS, C'EST NOTRE AFFAIRE!
					</h2>
					<h3 class="text-justify">
					Le Plaisir de Soigner collabore avec le réseau des soins de sante desservant les villes de Montréal, Québec, Saguenay.
					</h3>
				</div>
			</div>
			<div class="carousel-item">
				<div class="carousel-caption">
					<h2 class="text-center">
					VOS TALENTS, C'EST NOTRE AFFAIRE!
					</h2>
					<h4 class="text-justify">
					Nous savons bien qu'il faut plus que des comp&eacute;tences et de l'exp&eacute;rience sur papier pour &ecirc;tre le bon candidat. Notre processus approfondi de pr&eacute;s&eacute;lection, d'entrevue et d'&eacute;valuation des comp&eacute;tences assure la r&eacute;ussite des embauches
					</h4>
				</div>
			</div>
			<div class="carousel-item">
				<div class="carousel-caption">
					<h2 class="text-center">
					VOS TALENTS, C'EST NOTRE AFFAIRE!
					</h2>
					<h3 class="text-justify">
			Le Plaisir de Soigner est fier de soutenir les fondations Canadienne et Québécoise du cancer de sein.
					</h3>
				</div>
			</div>
			<div class="carousel-item">
				<div class="carousel-caption">
					<h2 class="text-center">
					VOS TALENTS, C'EST NOTRE AFFAIRE!
					</h2>
					<h3 class="text-justify">
					Nous sommes des experts dans notre domaine. Le Plaisir de Soigner a mis en place un système de classification de spécialités et de canalisation des professionnels de santé bien distincts pour la réussite de l’application d’embauche.    </h3>
				</div>
			</div>
		</div>
		<a class="carousel-control-prev d-none d-md-flex" href="#carouselExampleControls" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next d-none d-md-flex" href="#carouselExampleControls" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
		</div>
	</div>
</div>

<div class="row justify-content-center">
	<div class="col-12 col-md-10 mt-3">
		<div class="d-flex ">
			<img id="skyLine" src="{% static 'images/sky.jpg' %}" alt="" class="img-fluid pt-3 pb-3">
		</div>
	</div>
</div>
{% endblock %}

templates/home/personnel_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="topBanner">
</div>
<div class="content">
	<form id="staffForm" name="staffForm" method="post">
		<input type="hidden" name="staffFormSub" value="true">
		<fieldset>
			<legend><strong>Parlez à un expert</strong><br>
			<br>
			<p>En quête de personnel? Avec quelques détails seulement, nous pouvons désigner le gestionnaire en solutions de recrutement le mieux apte à satisfaire vos besoins et exigences d’embauche, qui communiquera avec vous pour lancer le processus.</p></legend>
			<br>
						<br><br><div class="thanks">Vos infos ont été transmises avec succès.  Le membre du personnel concerné vous contactera sous peu.</div>		</fieldset>
	</form>
</div>
{% endblock %}

templates/home/propose.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--<br>-->
<!--<br>-->
<br>
<br>
<div style=" margin: auto;
  width: 50%;
<!--  border: 3px solid green;-->
  padding: 10px;">

<iframe width="920" height="720" style="margin-left:auto; margin-right:auto; display:block;" src="https://www.youtube.com/embed/R6Km2MuXewU" frameborder="0" allowfullscreen></iframe>
</div>
<br>
<br>
<br>
<br>
{% endblock %}

templates/home/travailler.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row" id="topBanner2" >
	<div class="col 12 col-md-7 content mt-3 pt-3">
		<h1 class="col-6 d-none d-xl-block">TRAVAILLER</h1>
		<p class="d-none d-xl-block mt-3">Le plaisir de Soigner peut vous orienter vers des occasions de carri&egrave;re auxquelles vous n&rsquo;auriez pas acc&egrave;s autrement. Nous repr&eacute;sentons d&rsquo;excellents employeurs &ndash; dont un bon nombre pr&eacute;f&egrave;re collaborer exclusivement avec des experts en recrutement, sans faire de publicit&eacute; directe. Et si <em>vous</em> &eacute;tiez justement le genre de personnes qu&rsquo;ils recherchent?</p>
	</div>
</div>
<div class="work from-group">
	<form id="workForm" name="workForm" method="post" action="/jobs/">{% csrf_token %}
	<input type="hidden" name="searching" value="true" class="form-control">
	<label for="job-cat-home">RECHERCHE D'EMPLOI</label>
	<select id="job-cat-home" name="category">
		<option value="">Choisir une catégorie</option>
		<option value="5">Soins de santé</option><option value="41">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Infirmiers(ères)</option><option value="42">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Infirmiers(ères) auxiliaires</option><option value="43">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Préposés(ées) aux bénéficiaires</option><option value="44">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Aide aux familles</option>	</select>
	&nbsp
	<select name="city" class="mr-2">
		<option value="">Choisir un lieu</option>
		<option value="Québec">Québec</option><option value="Québec et les environs">  Québec et les environs</option><option value="Montréal (Région de)">  Montréal (Région de)</option><option value="Montréal – Centre">  Montréal – Centre</option><option value="Montréal – Laval & Rive Nord">  Montréal – Laval & Rive Nord</option><option value="Montréal – Rive Sud">  Montréal – Rive Sud</option><option value="Montréal – Ouest de l'Île">  Montréal – Ouest de l'Île</option><option value="Montréal – Est">  Montréal – Est</option><option value="Montréal - St-Laurent">  Montréal - St-Laurent</option><option value="Blainville/Laval Rive Nord">  Blainville/Laval Rive Nord</option><option value="Gatineau et les environs">  Gatineau et les environs</option><option value="Ontario"></select><br>
		<br>
	<input type="submit" name="workBtn" value="Recherche" id="searchBtn" >
<br><br>
Cliquez ici pour vous inscrire aux <a style="line-height: initial;" target="_blank" href="{% url 'home:cv' %}">ALERTES EMPLOI</a><br></form>
	<div class="content d-none d-md-block col-7">
		<h2>NOTRE APPROCHE</h2>
		<p class="mt-3">Votre CV ne dit pas tout. Nos clients veulent plus que des comp&eacute;tences et de l&#39;exp&eacute;rience sur papier, et nous avons &agrave; c&oelig;ur de faire des placements r&eacute;ussis et durables. C&#39;est pourquoi notre processus de s&eacute;lection de candidats est con&ccedil;u de mani&egrave;re &agrave; &eacute;valuer non seulement vos aptitudes et comp&eacute;tences, mais aussi votre personnalit&eacute; et vos attentes. En cernant mieux vos objectifs de carri&egrave;re, ce qui vous motive, et votre environnement de travail id&eacute;al, nos recruteurs peuvent assurer un jumelage parfait entre nos clients et nos candidats.Si vous avez pos&eacute; votre candidature &agrave; un poste et que votre profil correspond de pr&egrave;s aux exigences d&#39;un client, un recruteur communiquera avec vous pour lancer le processus de s&eacute;lection qui comprendra une combinaison d&#39;entrevues, de tests, de v&eacute;rification d&#39;ant&eacute;c&eacute;dents, et d&#39;obtention de r&eacute;f&eacute;rences.&nbsp;Il va sans dire que le simple fait de postuler ne garantit pas une convocation en entrevue. Vous voulez en savoir plus sur la fa&ccedil;on de faire des agences de recrutement priv&eacute;es? <img id="watch" src="{% static 'images/watch1.svg' %}" /></p>		<iframe width="560" height="315" style="margin-left:auto; margin-right:auto; display:block;" src="https://www.youtube.com/embed/R6Km2MuXewU" frameborder="0" allowfullscreen></iframe>
	</div>
</div>

{% endblock %}