home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('embaucher/', views.hire, name='hire'),
    path('cv/', views.cv, name='cv'),
    path('embaucher/personnel', views.personal, name='personal'),
    path('travailler/', views.work, name='work'),
    path('centre-de-carriere/', views.career_center, name='career_center'),
    path('contact/', views.contact, name='contact'),
    path('propose/', views.propose, name='propose'),
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', )),
                  path('manager/', include('manager.urls', namespace='manager')),
                  path('admin/', admin.site.urls),
                  path('jobs/', include('jobs.urls', namespace='jobs')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path

from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.manager, name='manager'),
    path('biography/', views.biography, name='biography'),
    path('biography/file_upload/', views.documentupload, name='uploadpdf'),
    path('biography/architect/', views.architect, name='architect'),
    path('deactivate/', views.deactivate, name='deactivate'),
    path('deactivate/account/', views.deactivate_account, name='deactivate_confirm'),
]

manager/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class CoverLetter(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cover_letter')
    cover_letter = models.TextField()
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}'s cover letter".format(self.user.username)

class Document_CV(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cv')
    document = models.FileField(upload_to='documents/%Y/%m/%d/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}'s cv".format(self.user.username)

manager/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import CoverLetter, Document_CV

class CoverLetterForm(forms.ModelForm):
    class Meta:
        model = CoverLetter
        fields = ('cover_letter',)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document_CV
        fields = ('document', )

    def clean_document(self):
        document = self.cleaned_data['document']

        try:
            #validate content type
            main, sub = document.content_type.split('/')
            if not (sub in ['pdf', 'doc', 'docx']):
                raise forms.ValidationError('Please use a pdf, or MS Word file.')

            #validate file size     # 4MB
            if len(document) > (4 * 1024000):
                raise forms.ValidationError('PDF file size may not exceed 4MBs.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new document
            """
            raise forms.ValidationError('You must provide a PDF file.')

        return document

manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import CoverLetterForm, DocumentForm
from .models import CoverLetter, Document_CV

# Create your views here.

@login_required
def manager(request):
    user = request.user
    return render(request, 'manager/manager.html')

@login_required
def biography(request):
    saved = None
    if request.method == 'POST':
        form = CoverLetterForm(request.POST, prefix='coverletter')
        if form.is_valid():
            cover_letter, created = CoverLetter.objects.get_or_create(user=request.user)
            cover_letter_content = form.cleaned_data['cover_letter']
            cover_letter.cover_letter = cover_letter_content
            cover_letter.save()
            saved = True
    else:
        form = CoverLetterForm(prefix='coverletter')
        form2 = DocumentForm(prefix='document') 
        saved = False
    return render(request, 'manager/biography.html', {'form': form, 'form2': form2, 'saved': saved})

@login_required
def documentupload(request):
    saved = None
    if request.method == 'POST':
        form2 = DocumentForm(request.POST, request.FILES, prefix='document')
        if form2.is_valid():
            cv, created = Document_CV.objects.get_or_create(user=request.user)
            cv_document = form2.cleaned_data['document']
            cv.document = cv_document
            cv.save()
            saved = True
    else:
        form2 = DocumentForm(prefix='document')  
        saved = False    
    return render(request, 'manager/upload_done.html', {'form': form2, 'saved': saved})


@login_required
def architect(request):
    return render(request, 'manager/architect.html')

@login_required
def deactivate(request):
    return render(request, 'manager/deactivate.html')   

@login_required
def deactivate_account(request):
    user = request.user
    user.is_active = False
    user.save()

    return redirect('home:index') 

templates/manager/biography.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="MainContent" style=""> 

      

  <script type="text/javascript" src="{% static 'script/biography.js' %}"></script>

  <center>
    <table class="DefaultTable">
      <tr>
        <td class="DefaultBottom">          
          <div class="fontcolor" style="text-align: left">
            <div class="quartermargin">
              <table style="width: 740px" cellpadding="1" cellspacing="1">
                <tr>
                  <td style="width: 365px; background-color: #d0dde7">
                    <span id="ctl00_Main_ResumeTitle" class="MainContentTitle" style="font-weight:bold;">CV</span>
                  </td>
                  <td style="width: 10px">
                  </td>
                  <td style="width: 365px; background-color: #d0dde7">
                    <span id="ctl00_Main_LetterTitle" class="MainContentTitle" style="font-weight:bold;">Lettre de motivation</span>
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; height: 10px">
                  </td>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px">
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; vertical-align: middle">
                    
                  </td>
                  <td style="width: 10px">
                  </td>
                  <td style="width: 365px; vertical-align: middle">
                    
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; height: 10px">
                  </td>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px">
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px">
                    <span id="ctl00_Main_ResumeText" class="AllText">Pour sauvegarder un nouveau CV &agrave; votre profil, vous pouvez:</span>
                  </td>
                  <td style="width: 10px">
                  </td>
                  <td style="width: 365px">
                    <span id="ctl00_Main_CoverText" class="AllText">Pour sauvegarder une nouvelle lettre de motivation &agrave; votre profil, vous pouvez:</span>
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; height: 10px">
                  </td>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px">
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; vertical-align: top;">
                    <div style="margin-left: 10px">
                      <div id="ctl00_Main_BuilderResumeLinkActive">
                        <input value="BuilderResumeRadioLink" name="ctl00$Main$Resume" type="radio" id="ctl00_Main_BuilderResumeRadioLink" onclick="javascript:resumebuilder();" class="AllText" tabindex="0" /><a href="{% url 'manager:architect' %}"><span id="ctl00_Main_BuilderResumeLink" class="AllLinks">Cr&eacute;er votre CV Quantum, &agrave; l&#39;aide de notre Profileur Quantum</span></a>
                      </div>
                    </div>
                    <div style="margin-left: 10px; margin-top: 10px;">
                      <div id="ctl00_Main_BuilderResumeLinkActive">
                        <input value="BuilderResumeRadioLink" name="ctl00$Main$Resume" type="radio" id="ctl00_Main_BuilderResumeRadioLink" onclick="javascript:resumebuilder();" class="AllText" tabindex="0" /><span id="ctl00_Main_BuilderResumeLink" class="AllLinks">Télécharger un nouveau fichier Télécharger votre CV en format PDF.</span>
                        {% if form2.errors %}
                          {{ form2.errors }}
                        {% endif %}
                        <form method="post" enctype="multipart/form-data" action="file_upload/">
                          {% csrf_token %}
                          {{ form2.as_p }}
                          <button type="submit">Upload</button>
                        </form>
                      
                        {% if uploaded_file_url %}
                          <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
                        {% endif %}
                      
                      </div>
                    </div>
                  </td>
                  <td style="width: 10px">
                  </td>
                  <td style="width: 365px">
                    <div style="margin-left: 10px">
                      <input value="BuilderLetterRadio" name="ctl00$Main$Letter" type="radio" id="ctl00_Main_BuilderLetterRadio" onclick="javascript:letterbuilder();" class="AllText" tabindex="0" /><span id="ctl00_Main_MemoLetterText" class="AllText">Cr&eacute;er un nouvelle lettre de motivation</span>
        
                      <div id="BuilderLetter" class="AllText">
                        <table>
                          <tr>
                            <td>
                            <form method="POST" action="."> {% csrf_token %} <!-- COVER LETTER -->
                              <textarea name="cover_letter" rows="2" cols="20" id="ctl00_Main_BuilderLetterTextBox" class="AllText" style="height:100px;width:320px;"></textarea>
                              <input type="submit" value="SAUVEGARDER LA NOUVELLE LETTRE" style="height:30px;width:275px;" />
                            </form>
                            {% if saved %}
                                <small style="color: red;">la lettre de motivation a été enregistrée avec succès.</small> 
                            {% endif %}
                            </td>
                          </tr>
                        </table>
                      </div>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px" align="center">
                  </td>
                </tr>
        
                <tr>
                  <td style="width: 365px; height: 10px" align="center">
                    
                  </td>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px" align="center">
                    &nbsp;
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; height: 10px">
                    <span id="ctl00_Main_ResumeNote" class="AllText">[Note: Sauvegarder un nouveau CV &eacute;crasera le courant]</span>
                  </td>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px">
                    <span id="ctl00_Main_LetterNote" class="AllText">[Note: Sauvegarder une nouvelle lettre de motivation &eacute;crasera celle courante]</span>
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px; height: 10px">
                  </td>
                  <td style="width: 10px; height: 10px">
                  </td>
                  <td style="width: 365px; height: 10px">
                  </td>
                </tr>
                <tr>
                  <td style="width: 365px" align="center">
                    <table border="0" width="200px" cellpadding="0" style="height: 140px; border-collapse: collapse">
                      <tr>
                        <td colspan="2" rowspan="2" class="CornerUpperLeft">
                        </td>
                        <td class="PatternHorizontal">
                        </td>
                        <td colspan="2" rowspan="2" class="CornerUpperRight">
                        </td>
                      </tr>
                      <tr>
                        <td style="height: 5px">
                        </td>
                      </tr>
                      <tr style="height: 140px">
                        <td class="PatternVertical">
                        </td>
                        <td style="width: 5px">
                        </td>
                        <td>
                          <div style="text-align: left">
                            <img alt="" src="{% static 'images/arrow_headers_alone.gif' %}" />&nbsp;&nbsp; <span id="ctl00_Main_ResumeHelpfulTip" class="MainContentTitle">Conseil</span><br />
                            <span id="ctl00_Main_ResumeHelpfulTipText" class="AllText">Attirez leur attention! Dites aux employeurs imm&#39;diatement ce qu&#39;ils veulent savoir sur vous. Le <b>premier tiers</b> de la page num&eacute;ro un est la partie la plus importante de votre C.V.</span></div>
                        </td>
                        <td style="width: 5px">
                        </td>
                        <td class="PatternVertical">
                        </td>
                      </tr>
                      <tr>
                        <td colspan="2" rowspan="2" class="CornerBottomLeft">
                        </td>
                        <td style="height: 5px">
                        </td>
                        <td colspan="2" rowspan="2" class="CornerBottomRight">
                        </td>
                      </tr>
                      <tr>
                        <td class="PatternHorizontal" style="height: 3px">
                        </td>
                      </tr>
                    </table>
                  </td>
                  <td style="width: 10px">
                  </td>
                  <td style="width: 365px" align="center">
                    <table border="0" width="200px" cellpadding="0" style="height: 140px; border-collapse: collapse">
                      <tr>
                        <td colspan="2" rowspan="2" class="CornerUpperLeft">
                        </td>
                        <td class="PatternHorizontal">
                        </td>
                        <td colspan="2" rowspan="2" class="CornerUpperRight">
                        </td>
                      </tr>
                      <tr>
                        <td style="height: 5px">
                        </td>
                      </tr>
                      <tr style="height: 140px">
                        <td class="PatternVertical">
                        </td>
                        <td style="width: 5px">
                        </td>
                        <td>
                          <div style="text-align: left">
                            <img alt="" src="{% static 'images/arrow_headers_alone.gif' %}" />&nbsp;&nbsp; <span id="ctl00_Main_LetterHelpfulTip" class="MainContentTitle">Conseil</span><br />
                            <div style="text-align: left">
                              <span id="ctl00_Main_LetterHelpfulTipText" class="AllText" style="text-align: left">Attirez leur attention! Dites aux employeurs imm&#39;diatement ce qu&#39;ils veulent savoir sur vous. Le <b>premier tiers</b> de la page num&eacute;ro un est la partie la plus importante de votre C.V.</span></div>
                        </td>
                        <td style="width: 5px">
                        </td>
                        <td class="PatternVertical">
                        </td>
                      </tr>
                      <tr>
                        <td colspan="2" rowspan="2" class="CornerBottomLeft">
                        </td>
                        <td style="height: 5px">
                        </td>
                        <td colspan="2" rowspan="2" class="CornerBottomRight">
                        </td>
                      </tr>
                      <tr>
                        <td class="PatternHorizontal" style="height: 3px">
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </div>
          </div>
          <div style="height: 200px">
          </div>
        </td>
      </tr>
    </table>
  </center>


                
  </div>
  
<script language='javascript' type='text/javascript'>
<!-- hide from non-javascript browsers
var radioresume = getElementByPartialName('BrowseResumeRadio', 'input');
radioresume.checked = true;
var browseresume = getElementByPartialName('ResumeBrowser', 'input');
browseresume.disabled = false;
var builderresumelink = getElementByPartialName('BuilderResumeLinkActive', 'div');
builderresumelink.style.display = 'none';
var radioletter = getElementByPartialName('BrowseLetterRadio', 'input');
radioletter.checked = true;
var browseletter = getElementByPartialName('LetterBrowser', 'input');
browseletter.disabled = false;
var builderletter = getElementByPartialName('BuilderLetterTextBox', 'textarea');
builderletter.disabled = true;
//-->
</script>


{% endblock %}

templates/manager/deactivate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

Are you sure you want to deactivate your account. Only admin will be able to activate it again.<a href="{% url 'manager:deactivate_confirm' %}" onclick="confirm('Are you sure?');"> Deactivate </a> 
{% endblock %}

templates/manager/upload_done.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}

    {% if saved %}
        <p>Your CV was uploaded successfully.</p>
    {% endif %}
{% endblock %}